import {PrismaClient,BookingStatus,InventoryStatus,PaymentStatus} from '@prisma/client';
import * as bcrypt from 'bcrypt';
const db=new PrismaClient();
const names=['Amina Kiptoo','Brian Mutai','Faith Chebet','Kevin Too','Mercy Jepchirchir','Dennis Kiplagat','Sharon Cherono','Ian Korir','Linet Jepkoech','Victor Keter','Winnie Chepkoech','Allan Rono','Sheila Moraa','Collins Kiptoo','Naomi Rotich','Mark Bett','Cynthia Jebet','Felix Kirwa','Grace Tanui','James Koech'];
async function main(){
 const role=await db.role.upsert({where:{name:'Super Administrator'},update:{},create:{name:'Super Administrator'}});
 const email=process.env.SEED_DEMO_ADMIN_EMAIL||'admin@veloraexperience.co.ke',password=process.env.SEED_DEMO_ADMIN_PASSWORD||'VeloraDemo#2026';
 const admin=await db.user.upsert({where:{email},update:{passwordHash:await bcrypt.hash(password,12)},create:{email,passwordHash:await bcrypt.hash(password,12),firstName:'Michelle',lastName:'Kiptoo',type:'ADMIN'}});
 await db.userRole.upsert({where:{userId_roleId:{userId:admin.id,roleId:role.id}},update:{},create:{userId:admin.id,roleId:role.id}});
 const zones=[];for(const [i,name]of ['Eldoret CBD','Elgon View','Pioneer','Annex','Kapsoya','Kimumu','Racecourse','West Indies'].entries()){const slug=name.toLowerCase().replaceAll(' ','-');zones.push(await db.serviceZone.upsert({where:{slug},update:{},create:{name,slug,deliveryFee:400+i*100,setupFee:300,minimumOrder:3500}}))}
 const packageData=[['The Essential','essential',4500,1,3],['The Social','social',8500,2,6],['Rooftop Afterglow','rooftop',12500,2,8],['The Night Edition','night',16500,3,12],['Birthday Lounge','birthday',22500,3,6],['Full-Day Experience','full-day',28000,4,24]] as const;
 const packages=[];for(const [name,slug,basePrice,includedSetups,includedHours]of packageData)packages.push(await db.experiencePackage.upsert({where:{slug},update:{},create:{name,slug,basePrice,includedSetups,includedHours,description:`A premium ${name.toLowerCase()} prepared by Velora.`,durations:{create:[3,4,6,8,12,18,24].map(hours=>({hours,price:Math.max(0,hours-includedHours)*850}))}}}));
 const cat=await db.flavourCategory.upsert({where:{name:'Velora Edit'},update:{},create:{name:'Velora Edit'}});for(const [i,name]of ['Double Apple','Blue Mist','Grape Mint','Watermelon Chill','Mango Ice','Peach Breeze','Lemon Mint','Berry Fusion','Pineapple Wave','Passion Citrus','Mint Royale','Velora Signature'].entries()){const slug=name.toLowerCase().replaceAll(' ','-');await db.flavour.upsert({where:{slug},update:{},create:{name,slug,description:`A refined ${name} blend.`,tastingNotes:'Layered, fresh and balanced',surcharge:i>9?300:0,categoryId:cat.id}})}
 for(const [i,name]of ['Extra hose','Premium LED base','Additional setup','Mouthpiece pack','Ambient lighting','Lounge decor','Bluetooth speaker','Event attendant','Priority delivery','Late-night collection'].entries()){const slug=name.toLowerCase().replaceAll(' ','-');await db.addOn.upsert({where:{slug},update:{},create:{name,slug,price:500+i*250}})}
 const category=await db.inventoryCategory.upsert({where:{name:'Premium setups'},update:{},create:{name:'Premium setups'}});for(let i=1;i<=30;i++){const code=`VLR-POT-${String(i).padStart(3,'0')}`;await db.inventoryAsset.upsert({where:{code},update:{},create:{code,name:`Velora Premium Setup ${i}`,categoryId:category.id,replacementValue:18000,status:i===29?InventoryStatus.DAMAGED:i===30?InventoryStatus.MAINTENANCE:InventoryStatus.AVAILABLE}})}
 const customers=[];for(const [i,name]of names.entries()){const phone=`+25470010${String(i).padStart(4,'0')}`;customers.push(await db.customerProfile.upsert({where:{phone},update:{},create:{name,phone,email:`guest${i+1}@velora.demo`}}))}
 if(await db.booking.count()===0){const statuses=Object.values(BookingStatus);for(let i=0;i<25;i++){const pkg=packages[i%6],customer=customers[i%20],zone=zones[i%8],total=pkg.basePrice+zone.deliveryFee+zone.setupFee+1500;const booking=await db.booking.create({data:{reference:`VLR-2607-${1100+i}`,trackingPin:String(4100+i),customerId:customer.id,packageId:pkg.id,zoneId:zone.id,status:statuses[i%statuses.length],paymentStatus:i%3===0?PaymentStatus.PAID:PaymentStatus.UNPAID,setups:pkg.includedSetups,durationHours:pkg.includedHours,deliveryAt:new Date(Date.now()+(i-5)*86400000),eventType:i%4===0?'Birthday':'Home session',guestCount:4+i,addressSnapshot:{building:`Demo residence ${i+1}`},locationType:i%2?'Indoor':'Outdoor',pricingSnapshot:{total},total,history:{create:{status:statuses[i%statuses.length]}}}});if(i%3===0)await db.payment.create({data:{bookingId:booking.id,amount:total,method:'M-PESA_ON_DELIVERY',status:'PAID',reference:`DEMO-${i}`}})}}
 await db.promotion.upsert({where:{code:'VELORA10'},update:{},create:{code:'VELORA10',type:'PERCENT',value:10,startsAt:new Date(),endsAt:new Date(Date.now()+90*86400000)}});console.log('Velora demo database seeded');
}
main().finally(()=>db.$disconnect());
