'use client';
import Link from 'next/link'; import {useState} from 'react';
import {Header,Footer} from '@/components/Site'; import {packages,flavours,money} from '@/lib/data';
export default function Home(){const [mood,setMood]=useState('Chill'); return <main><Header/><section className="hero"><div className="heroImage"/><div className="heroShade"/><div className="heroCopy"><div className="eyebrow">VELORA EXPERIENCE · ELDORET</div><h1>Premium moments,<br/><i>delivered.</i></h1><p>A professionally prepared shisha experience for your home, rooftop, birthday or private event. We deliver, install, support and collect.</p><div className="actions"><Link className="button" href="/book">Book an experience <span>→</span></Link><Link className="ghost" href="/experiences">Explore packages</Link></div><div className="serving"><span>●</span> Currently serving Eldoret Urban</div></div><div className="scroll">SCROLL TO DISCOVER ↓</div></section>
<section className="intro"><div className="eyebrow">THE VELORA STANDARD</div><h2>More than a setup.<br/><i>A complete experience.</i></h2><p>From preparation to collection, every detail is handled with the care of premium hospitality.</p><div className="benefits">{[['01','Immaculately prepared','Sanitised, quality-checked equipment.'],['02','Delivered with care','Reliable arrival and discreet setup.'],['03','Supported throughout','A dedicated team when you need us.']].map(x=><article key={x[0]}><em>{x[0]}</em><h3>{x[1]}</h3><p>{x[2]}</p></article>)}</div></section>
<section className="darkSection"><div className="sectionHead"><div><div className="eyebrow">CURATED EXPERIENCES</div><h2>Choose your <i>moment.</i></h2></div><Link href="/experiences">View all experiences →</Link></div><div className="packageGrid">{packages.slice(0,4).map((x,i)=><Link href={'/experiences/'+x.slug} className={'package '+x.tone} key={x.slug}><span>0{i+1}</span><div><small>{x.tag}</small><h3>{x.name}</h3><p>{x.meta}</p><b>From {money(x.price)}</b></div></Link>)}</div></section>
<section id="how" className="steps"><div><div className="eyebrow">EFFORTLESS BY DESIGN</div><h2>Your evening,<br/><i>beautifully handled.</i></h2></div><div>{['Choose your experience','Personalise every detail','We deliver & set up','Enjoy. We handle the rest.'].map((x,i)=><article key={x}><b>0{i+1}</b><h3>{x}</h3><p>{['Select a curated package or build your own.','Pick flavours, duration and thoughtful extras.','Our team arrives, installs and prepares everything.','Extend in a tap; we return for collection.'][i]}</p></article>)}</div></section>
<section className="mood"><div className="eyebrow">SET THE MOOD</div><h2>What does tonight <i>feel like?</i></h2><div className="moods">{['Chill','Celebration','Rooftop','Intimate','Premium','Late Night'].map(x=><button className={mood===x?'active':''} onClick={()=>setMood(x)} key={x}>{x}</button>)}</div><div className="recommend"><span>Recommended for {mood}</span><h3>{mood==='Celebration'?'Birthday Lounge':mood==='Rooftop'?'Rooftop Afterglow':mood==='Late Night'?'The Night Edition':'The Social'}</h3><Link href="/book">Personalise this experience →</Link></div></section>
<section className="flavourPreview"><div className="sectionHead"><div><div className="eyebrow">THE FLAVOUR EDIT</div><h2>Curated notes.<br/><i>Unforgettable blends.</i></h2></div><Link href="/flavours">Explore all flavours →</Link></div><div className="flavourRow">{flavours.slice(0,4).map((x,i)=><article key={x.name}><span>0{i+1}</span><small>{x.cat}</small><h3>{x.name}</h3><p>{x.note}</p></article>)}</div></section><Footer/></main>}
