'use client';
import Link from 'next/link';import {useEffect,useState} from 'react';import {Logo,Status} from './Site';import {TimeGreeting} from './TimeGreeting';import {orders,packages,flavours} from '@/lib/data';

const menu=['Overview','Orders','Dispatch','Customers','Inventory','Packages','Flavours','Service zones','Staff','Payments','Analytics','Audit log','Settings'];
const slug=(x:string)=>x.toLowerCase().replaceAll(' ','-');
const customers=[['Amina Kiptoo','+254 700 104 821','6','KSh 58,400','Elgon View'],['Brian Mutai','+254 711 820 441','4','KSh 39,700','Pioneer'],['Faith Chebet','+254 722 501 946','8','KSh 91,200','Kapsoya'],['Kevin Too','+254 733 160 285','3','KSh 47,500','Kimumu'],['Mercy Jepchirchir','+254 748 320 194','5','KSh 64,800','Eldoret CBD']];
const inventory=[['VLR-POT-001','Obsidian Glass Setup','Premium setups','Available','Velora Hub'],['VLR-POT-008','Crystal Lounge Setup','Premium setups','Reserved','Birthday Lounge'],['VLR-LED-004','Champagne LED Base','Lighting','At customer','VLR-2607-1591'],['VLR-HOSE-012','Velvet Hose · Plum','Accessories','Cleaning','Velora Hub'],['VLR-POT-029','Midnight Stem Set','Premium setups','Damaged','Assessment bay'],['VLR-SPK-002','Marshall Speaker','Audio','Maintenance','Workshop']];
const staff=[['Collins Rono','Delivery & Setup','Out for delivery','2 jobs'],['Sharon Chebet','Experience Attendant','Available','1 job'],['Dennis Kiplagat','Delivery & Setup','At customer','3 jobs'],['Mercy Tanui','Dispatch Manager','Operations hub','6 jobs'],['Brian Keter','Collection Team','Collecting','2 jobs']];
const zones=[['Eldoret CBD','KSh 400','25–35 min','Active'],['Elgon View','KSh 500','30–40 min','Active'],['Pioneer','KSh 600','35–45 min','Active'],['Annex','KSh 700','40–50 min','Active'],['Kapsoya','KSh 800','40–55 min','Active'],['Kimumu','KSh 900','45–60 min','Active']];

function Title({eyebrow,title,copy,action}:{eyebrow:string;title:string;copy:string;action?:string}){return <div className="adminHeading"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{copy}</p></div>{action&&<button className="button">+ {action}</button>}</div>}
function DataTable({headers,rows}:{headers:string[];rows:(string|React.ReactNode)[][]}){return <div className="tableWrap"><table className="table adminTable"><thead><tr>{headers.map(x=><th key={x}>{x}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i}>{row.map((cell,j)=><td key={j}>{cell}</td>)}</tr>)}</tbody></table></div>}
function Overview(){return <><Title eyebrow="SATURDAY, 18 JULY" title="Operations overview" copy="A live view of revenue, active experiences and today’s service readiness." action="New booking"/><div className="welcome"><TimeGreeting/><span>Here’s what needs your attention today.</span></div><div className="kpis">{[['Revenue today','KSh 86,400','↑ 18.4%'],['Active experiences','8','3 collections due'],['New bookings','12','4 awaiting review'],['Available setups','18 / 32','56% availability']].map(x=><article className="kpi" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span className="up">{x[2]}</span></article>)}</div><div className="adminGrid"><article className="card"><h3>Revenue this week</h3><small>KSh 384,200 · +12.8% vs last week</small><div className="bars">{[38,56,44,75,62,91,70].map((x,i)=><i key={i} style={{height:x+'%'}}/>)}</div></article><article className="card"><h3>Today’s operations</h3>{[['Awaiting confirmation','4'],['Preparing','3'],['Out for delivery','2'],['Experiences active','8'],['Collections due','5']].map(x=><div className="line" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</article></div><article className="card"><h3>Live bookings</h3><OrdersTable/></article></>}
function OrdersTable(){return <DataTable headers={['Reference','Customer','Experience','Zone / arrival','Total','Status']} rows={orders.map(x=>[<b key={x.ref}>{x.ref}</b>,x.customer,x.experience,<span key={x.zone}>{x.zone}<br/><small>{x.time}</small></span>,x.total,<Status key={x.status}>{x.status}</Status>])}/>}
function Orders(){return <><Title eyebrow="BOOKING OPERATIONS" title="Orders" copy="Search, confirm and coordinate every Velora experience from request to collection." action="Manual booking"/><div className="toolbar"><input placeholder="Search reference, customer or phone…"/><button className="chip active">All orders · 25</button><button className="chip">Awaiting · 4</button><button className="chip">Active · 8</button><button className="chip">Completed · 9</button></div><article className="card"><OrdersTable/></article></>}
function Dispatch(){const jobs=[['17:30','VLR-2607-1739','Brian M. · Pioneer','Collins Rono','Out for delivery'],['19:00','VLR-2607-1842','Amina K. · Elgon View','Unassigned','Awaiting confirmation'],['20:00','VLR-2607-1688','Faith C. · Kapsoya','Dennis Kiplagat','Preparing'],['23:30','VLR-2607-1591','Kevin T. · Kimumu','Brian Keter','Collection due']];return <><Title eyebrow="LIVE ROUTE BOARD" title="Dispatch" copy="Coordinate deliveries, setup teams and collection windows across Eldoret."/><div className="dispatchStats">{[['Next departure','17:10'],['Teams on road','3'],['Unassigned jobs','1'],['On-time rate','94%']].map(x=><div key={x[0]}><small>{x[0]}</small><b>{x[1]}</b></div>)}</div><article className="card"><h3>Today’s route timeline</h3><DataTable headers={['Time','Booking','Destination','Assigned team','Status']} rows={jobs.map(x=>[x[0],<b key={x[1]}>{x[1]}</b>,x[2],x[3],<Status key={x[4]}>{x[4]}</Status>])}/></article></>}
function Customers(){return <><Title eyebrow="RELATIONSHIPS" title="Customers" copy="Profiles, booking history, preferences and account standing." action="Add customer"/><div className="kpis">{[['Total customers','284','+22 this month'],['Repeat rate','38%','↑ 4.2%'],['Average spend','KSh 14,860','Last 90 days'],['VIP customers','17','Top 6%']].map(x=><article className="kpi" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span></article>)}</div><article className="card"><DataTable headers={['Customer','Phone','Bookings','Lifetime value','Preferred zone']} rows={customers.map(x=>[<b key={x[0]}>{x[0]}</b>,x[1],x[2],x[3],x[4]])}/></article></>}
function Inventory(){return <><Title eyebrow="ASSET CONTROL" title="Inventory" copy="Availability, condition, cleaning and reservation status for every physical asset." action="Add asset"/><div className="inventoryMeter"><div><b>18</b><span>Available</span></div><div><b>7</b><span>Reserved</span></div><div><b>3</b><span>At customer</span></div><div><b>2</b><span>Attention</span></div></div><article className="card"><DataTable headers={['Asset code','Asset','Category','Status','Location / assignment']} rows={inventory.map(x=>[<b key={x[0]}>{x[0]}</b>,x[1],x[2],<Status key={x[3]}>{x[3]}</Status>,x[4]])}/></article></>}
function Packages(){return <><Title eyebrow="EXPERIENCE CATALOGUE" title="Packages" copy="Curate inclusions, durations and presentation order across customer channels." action="New package"/><div className="managementGrid">{packages.map(x=><article className="manageCard" key={x.slug}><span className={'manageSwatch '+x.tone}/><small>{x.meta}</small><h3>{x.name}</h3><b>KSh {x.price.toLocaleString()}</b><div><Status>Active</Status><button>Manage →</button></div></article>)}</div></>}
function Flavours(){return <><Title eyebrow="FLAVOUR INVENTORY" title="Flavours" copy="Manage availability, tasting notes, premium surcharges and stock thresholds." action="Add flavour"/><article className="card"><DataTable headers={['Flavour','Category','Tasting notes','Stock','Surcharge','Status']} rows={flavours.map((x,i)=>[<b key={x.name}>{x.name}</b>,x.cat,x.note,`${12+i*3} portions`,i<2?'KSh 300':'—',<Status key={x.name}>In stock</Status>])}/></article></>}
function Zones(){return <><Title eyebrow="DELIVERY COVERAGE" title="Service zones" copy="Control fees, arrival estimates, late-night coverage and minimum booking values." action="Add zone"/><article className="card"><DataTable headers={['Zone','Delivery fee','ETA','Late night','Status']} rows={zones.map(x=>[<b key={x[0]}>{x[0]}</b>,x[1],x[2],'Available',<Status key={x[0]}>{x[3]}</Status>])}/></article></>}
function Staff(){return <><Title eyebrow="PEOPLE & PERMISSIONS" title="Staff" copy="Team availability, operational roles and today’s assigned workload." action="Invite staff"/><div className="staffGrid">{staff.map((x,i)=><article className="staffCard" key={x[0]}><div className="avatar">{x[0].split(' ').map(n=>n[0]).join('')}</div><div><h3>{x[0]}</h3><p>{x[1]}</p><Status>{x[2]}</Status><small>{x[3]}</small></div><button>•••</button></article>)}</div></>}
function Payments(){const rows=[['PAY-8841','VLR-2607-1591','M-Pesa on delivery','KSh 31,500','Paid'],['PAY-8836','VLR-2607-1739','Cash on delivery','KSh 5,000','Partially paid'],['DEP-2044','VLR-2607-1842','Equipment deposit','KSh 4,500','Deposit held'],['PAY-8829','VLR-2607-1688','M-Pesa on delivery','KSh 18,900','Pending']];return <><Title eyebrow="FINANCIAL OPERATIONS" title="Payments" copy="Manual collections, outstanding balances, deposits and reconciliation." action="Record payment"/><div className="kpis">{[['Collected today','KSh 62,900','14 payments'],['Outstanding','KSh 28,300','6 bookings'],['Deposits held','KSh 42,000','11 deposits'],['Refunds pending','KSh 3,500','1 request']].map(x=><article className="kpi" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span>{x[2]}</span></article>)}</div><article className="card"><DataTable headers={['Reference','Booking','Method','Amount','Status']} rows={rows.map(x=>[<b key={x[0]}>{x[0]}</b>,x[1],x[2],x[3],<Status key={x[4]}>{x[4]}</Status>])}/></article></>}
function Analytics(){return <><Title eyebrow="BUSINESS INTELLIGENCE" title="Analytics" copy="Performance signals across revenue, packages, durations and service areas."/><div className="kpis">{[['Revenue this month','KSh 1.42M','↑ 16.8%'],['Average order','KSh 15,240','↑ KSh 860'],['Utilisation','72%','Peak: 89%'],['Completion rate','96.4%','↑ 1.2%']].map(x=><article className="kpi" key={x[0]}><small>{x[0]}</small><b>{x[1]}</b><span className="up">{x[2]}</span></article>)}</div><div className="adminGrid"><article className="card"><h3>30-day revenue</h3><div className="bars analyticsBars">{[22,30,28,47,38,54,43,61,58,72,64,83,76,92].map((x,i)=><i key={i} style={{height:x+'%'}}/>)}</div></article><article className="card"><h3>Top experiences</h3>{[['The Social','31%'],['Birthday Lounge','24%'],['Night Edition','19%'],['The Essential','16%']].map(x=><div className="metric" key={x[0]}><span>{x[0]}</span><div><i style={{width:x[1]}}/></div><b>{x[1]}</b></div>)}</article></div></>}
function Audit(){const events=[['17:12','Michelle Kiptoo','Changed VLR-2607-1739 to Out for delivery','Booking'],['16:48','Mercy Tanui','Assigned Collins Rono to delivery job','Dispatch'],['16:31','Michelle Kiptoo','Recorded M-Pesa payment of KSh 31,500','Payment'],['15:55','Dennis Kiplagat','Uploaded setup confirmation','Delivery proof'],['15:20','System','Reserved VLR-POT-008 for Birthday Lounge','Inventory']];return <><Title eyebrow="SECURITY & TRACEABILITY" title="Audit log" copy="An immutable operational record of sensitive administrative actions."/><article className="card auditList">{events.map(x=><div key={x[0]}><time>{x[0]}</time><span><b>{x[1]}</b><p>{x[2]}</p></span><small>{x[3]}</small></div>)}</article></>}
function Settings(){return <><Title eyebrow="BUSINESS CONFIGURATION" title="Settings" copy="Control booking policy, operating hours, notifications and demo safeguards."/><div className="settingsGrid">{[['Booking rules','Minimum duration','3 hours'],['Responsible use','Minimum customer age','18 years'],['Operations','Same-day cut-off','5:00 PM'],['Collection','Default grace period','30 minutes'],['Notifications','Provider','Mock · logs enabled'],['Payments','Provider','Manual collection']].map(x=><article className="card" key={x[1]}><small>{x[0]}</small><h3>{x[1]}</h3><div className="settingValue">{x[2]}<button>Edit</button></div></article>)}</div></>}

function Content({view}:{view:string}){switch(view){case'orders':return <Orders/>;case'dispatch':return <Dispatch/>;case'customers':return <Customers/>;case'inventory':return <Inventory/>;case'packages':return <Packages/>;case'flavours':return <Flavours/>;case'service-zones':return <Zones/>;case'staff':return <Staff/>;case'payments':return <Payments/>;case'analytics':return <Analytics/>;case'audit-log':return <Audit/>;case'settings':return <Settings/>;default:return <Overview/>}}

export function AdminConsole(){const [view,setView]=useState('overview'),[navOpen,setNavOpen]=useState(false);useEffect(()=>{const sync=()=>setView(slug(decodeURIComponent(location.hash.slice(1)))||'overview');sync();addEventListener('hashchange',sync);return()=>removeEventListener('hashchange',sync)},[]);return <main className="admin"><div className="adminTop"><Logo/><button className="adminNavToggle" onClick={()=>setNavOpen(!navOpen)}>☰ Menu</button><span>Super Administrator · <b>Demo</b></span></div><div className="adminLayout"><aside className={'sidebar '+(navOpen?'open':'')}>{menu.map(x=><Link onClick={()=>setNavOpen(false)} key={x} className={view===slug(x)?'active':''} href={x==='Overview'?'/admin':'/admin#'+slug(x)}>{x}</Link>)}</aside><section className="adminMain"><Content view={view}/></section></div></main>}
