import {Body,Controller,Injectable,Post,UnauthorizedException} from '@nestjs/common';
import {JwtService} from '@nestjs/jwt';import {IsEmail,IsString,MinLength} from 'class-validator';import * as bcrypt from 'bcrypt';import {createHash,randomBytes} from 'crypto';import {PrismaService} from './prisma.service';
export class LoginDto{@IsEmail() email!:string;@IsString() @MinLength(8) password!:string}
export class RegisterDto extends LoginDto{@IsString() firstName!:string;@IsString() lastName!:string;@IsString() phone!:string}
@Injectable() export class AuthService{constructor(private db:PrismaService,private jwt:JwtService){}
  private async tokens(user:{id:string;email:string;type:string}){const payload={sub:user.id,email:user.email,type:user.type};const accessToken=await this.jwt.signAsync(payload,{secret:process.env.JWT_ACCESS_SECRET,expiresIn:'15m'});const refreshToken=randomBytes(48).toString('base64url');await this.db.refreshToken.create({data:{userId:user.id,tokenHash:createHash('sha256').update(refreshToken).digest('hex'),expiresAt:new Date(Date.now()+30*86400000)}});return{accessToken,refreshToken,user:{id:user.id,email:user.email,type:user.type}}}
  async login(dto:LoginDto){const user=await this.db.user.findUnique({where:{email:dto.email.toLowerCase()}});if(!user||!user.active||!await bcrypt.compare(dto.password,user.passwordHash))throw new UnauthorizedException('Invalid email or password');return this.tokens(user)}
  async register(dto:RegisterDto){const passwordHash=await bcrypt.hash(dto.password,12);const user=await this.db.user.create({data:{email:dto.email.toLowerCase(),passwordHash,firstName:dto.firstName,lastName:dto.lastName,phone:dto.phone,customer:{create:{name:`${dto.firstName} ${dto.lastName}`,phone:dto.phone,email:dto.email}}}});return this.tokens(user)}
  async refresh(token:string){const hash=createHash('sha256').update(token).digest('hex');const stored=await this.db.refreshToken.findUnique({where:{tokenHash:hash},include:{user:true}});if(!stored||stored.revokedAt||stored.expiresAt<new Date())throw new UnauthorizedException('Refresh token expired');await this.db.refreshToken.update({where:{id:stored.id},data:{revokedAt:new Date()}});return this.tokens(stored.user)}
  async logout(token:string){await this.db.refreshToken.updateMany({where:{tokenHash:createHash('sha256').update(token).digest('hex')},data:{revokedAt:new Date()}});return{success:true}}
}
@Controller('auth') export class AuthController{constructor(private service:AuthService){}@Post('login')login(@Body() dto:LoginDto){return this.service.login(dto)}@Post('register')register(@Body() dto:RegisterDto){return this.service.register(dto)}@Post('refresh')refresh(@Body('refreshToken') t:string){return this.service.refresh(t)}@Post('logout')logout(@Body('refreshToken') t:string){return this.service.logout(t)}}
